import type { Metadata } from "next";
import {DataProvider} from "../contexts/Data";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
   
      <body><DataProvider>{children}</DataProvider></body>
    </html>
  );
}
